[package]
name = "gdl-parser"
version = "0.0.8"
authors = ["Gulshan Singh <gulshan@umich.edu>"]
description = "A parser for GDL (game description language)"
license = "MIT"
repository = "https://github.com/gsingh93/gdl-parser"

[dependencies]
rustc-serialize = "*"
